spring:

  application:
    name: dash

  security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}
              scope: [profile, email]
              # ------------------------------------------------------------
              # [Spring Boot가 자동 설정해 주는 기본값]
              # client-name: Google
              # authorization-grant-type: authorization_code
              # redirect-uri: {baseUrl}/login/oauth2/code/{registrationId}
              # (기본값 예시: http://localhost:8080/login/oauth2/code/google)
              # ------------------------------------------------------------
  
  datasource:
    url: jdbc:mysql://localhost:3306/dash_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
